export const state = {
  tracks: [],
  current: -1,
  playing: false,
  shuffle: false,
  repeat: 'none',
  volume: 0.8,
  muted: false,
  seekDrag: false,
  volDrag: false,
  alwaysOnTop: false,
  miniPlayer: false,
  shuffleOrder: [],
  lang: 'ja',
  theme: 'dark',
  speed: 1.0,
  version: '0.0.0',
};
